#code morse

def morse():
    print("""
    1. Encriptar
    2. Desencriptar""")
    opcion = int(input("Ingrese una opcion: "))
    if opcion == 1:
        print("Encriptar")
        texto = input("Ingrese el texto a encriptar: ")
        texto = texto.upper()
        texto = texto.replace("A", ".-")
        texto = texto.replace("B", "-...")
        texto = texto.replace("C", "-.-.")
        texto = texto.replace("D", "-..")
        texto = texto.replace("E", ".")
        texto = texto.replace("F", "..-.")
        texto = texto.replace("G", "--.")
        texto = texto.replace("H", "....")
        texto = texto.replace("I", "..")
        texto = texto.replace("J", ".---")
        texto = texto.replace("K", "-.-")
        texto = texto.replace("L", ".-..")
        texto = texto.replace("M", "--")
        texto = texto.replace("N", "-.")
        texto = texto.replace("O", "---")
        texto = texto.replace("P", ".--.")
        texto = texto.replace("Q", "--.-")
        texto = texto.replace("R", ".-.")
        texto = texto.replace("S", "...")
        texto = texto.replace("T", "-")
        texto = texto.replace("U", "..-")
        texto = texto.replace("V", "...-")
        texto = texto.replace("W", ".--")
        texto = texto.replace("X", "-..-")
        texto = texto.replace("Y", "-.--")
        texto = texto.replace("Z", "--..")
        texto = texto.replace("0", "-----")
    elif opcion == 2:
        texto = input("Ingrese el texto a desencriptar: ")
        texto = texto.upper()
        texto = texto.replace("-.-", "A")
        texto = texto.replace("-...", "B")
        texto = texto.replace("-.-.", "C")
        texto = texto.replace("-..", "D")
        texto = texto.replace(".", "E")
        texto = texto.replace("..-.", "F")
        texto = texto.replace("--.", "G")
        texto = texto.replace("....", "H")
        texto = texto.replace("..", "I")
        texto = texto.replace(".---", "J")
        texto = texto.replace("-.-", "K")
        texto = texto.replace(".-..", "L")
        texto = texto.replace("--", "M")
        texto = texto.replace("-.", "N")
        texto = texto.replace("---", "O")
        texto = texto.replace(".--.", "P")
        texto = texto.replace("--.-", "Q")
        texto = texto.replace(".-.", "R")
        texto = texto.replace("...", "S")
        texto = texto.replace("-", "T")
        texto = texto.replace("..-", "U")
        texto = texto.replace("...-", "V")
        texto = texto.replace(".--", "W")
        texto = texto.replace("-..-", "X")  
        texto = texto.replace("-.--", "Y")
    return print(texto)
        
morse()